ALTER TABLE "user_settings"
  ADD COLUMN "micGain" INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN "outputGain" INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN "noiseSuppressionMode" TEXT NOT NULL DEFAULT 'auto',
  ADD COLUMN "noiseGate" INTEGER NOT NULL DEFAULT 40,
  ADD COLUMN "pushToTalkEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "keybinds" JSONB;
